FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
RUN yarn cache clean
RUN yarn
RUN yarn global add ts-node
RUN yarn global add typescript
RUN yarn global add mocha
COPY . .
CMD ["yarn", "run", "test"]